name: Cancel
on:
  workflow_run:
    workflows: ['automerge', 'build', 'codeql-analysis']
    types:
      - requested
permissions:
  actions: write
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@dee858fff096b2cbcd4f845ce21871c50c5af452
        name: Cancel Previous Workflow Runs
        with:
          workflow_id: ${{ github.event.workflow.id }}
